name: GET_REGISTRATIONS
on: 
  schedule:
    - cron: '0 0 * * *' 

jobs:
  get_registrations:
    runs-on: ubuntu-latest
    steps:
   # - name: Create cache file
   #   run: mkdir check-SHA; echo ${{ github.sha }} > github-sha.txt; cat github-sha.txt
    #===============================================#
   # - name: Check SHA
   #   id: check_sha
   #   uses: actions/cache@v1
   #   with:
   #     path: check-SHA
   #     key: check-SHA-${{ github.sha }}
    #===============================================#
   # - name: Some subsequent steps
   #   if: steps.check_sha.outputs.cache-hit == 'true'
   #   run: echo "Cache hit not found...Execute the subsequent steps"; exit 1 # no way to exit nicely?
    #===============================================#
    - name: Access biopypir website
      run:    curl -o registrations.json https://biopypir/registrations.json

    - name:  CHECKOUT ${{env.OWNER}} ${{env.PACKAGE}} 
      uses: actions/checkout@v2     
      with:
        repository: ${{env.Owner_Repo}} 

    - name: Add & Commit 
      #if: always()
      uses: EndBug/add-and-commit@v4.1.0

      with:
        add: .  #${{env.PACKAGE}}_${{github.run_id}}.json
        message: 'Commit ${{env.PACKAGE}} workflow run # ${{github.run_number}}  (${{env.biopypir_workflow_status}})'
        ref: 'logs' 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
