---
name: BIOPYPIR
on: 
  repository_dispatch:
     types: [autorun]
     
  #schedule:
  #  - cron: '0 0 * * 0' 
  #push: # remove when youre done testing workflow
  #  paths-ignore: 
  #    - 'logs/**.json' 
  #    - 'biopypir_matrix.md'
  #    -  'utils/package_params.json'
  #  get linux distribution 
    
jobs:
  run_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6,3.7] 
        os: [ubuntu-latest] #,windows-latest, macOS-latest] 
    steps:
   # - name: Create cache file
   #   run: mkdir check-SHA; echo ${{ github.sha }} > github-sha.txt; cat github-sha.txt
    #===============================================#
   # - name: Check SHA
   #   id: check_sha
   #   uses: actions/cache@v1
   #   with:
   #     path: check-SHA
   #     key: check-SHA-${{ github.sha }}
    #===============================================#
   # - name: Some subsequent steps
   #   if: steps.check_sha.outputs.cache-hit == 'true'
   #   run: echo "Cache hit not found...Execute the subsequent steps"; exit 1 # no way to exit nicely?
    #===============================================#
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    
    - name: set environment variables
      run: |     #echo "${{ github.event.client_payload.PACKAGE }}"
        echo "PACKAGE=${{ github.event.client_payload.PACKAGE }}" >> $GITHUB_ENV
        echo "OWNER=${{ github.event.client_payload.OWNER }}" >> $GITHUB_ENV
        echo "Owner_Repo=${{ github.event.client_payload.Owner_Repo }}" >> $GITHUB_ENV
        echo "test_suite=${{ github.event.client_payload.test_suite }}" >> $GITHUB_ENV
        echo "test_dir=${{ github.event.client_payload.tests_dir }}" >> $GITHUB_ENV
        echo "ignore_tests=${{ github.event.client_payload.ignore_tests }}" >> $GITHUB_ENV
        echo "ignore_lint=${{ github.event.client_payload.ignore_lint }}" >> $GITHUB_ENV
        echo "PIP_TEST=${{ github.event.client_payload.pip }}" >> $GITHUB_ENV

    #===============================================#
    - name:  CHECKOUT ${{env.OWNER}} ${{env.PACKAGE}} 
      uses: actions/checkout@v2     
      with:
        repository: ${{env.Owner_Repo}} 
    
    - name: Get Workflow Helper
      run: |
        curl -L -o biopypir_utils.sh "https://raw.githubusercontent.com/benstear/biopypir_logs/master/utils/workflow_helper.sh"      
        chmod +x biopypir_utils.sh  
    #    ./biopypir_utils.sh  "SET ENV"  

    - name: Set Up ${{matrix.os}}-py${{matrix.python-version}}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}   
    #===============================================#
    - name: INSTALL dependencies                         #  how to handle this step?
      run: |
        pip install --upgrade pip setuptools wheel  
        pip install pylint
        pip install pytest
        pip install coverage
        pip install pytest-cov
        pip install pytest-mpl    
    #===============================================#
    - name: LINT
      id: linter
      run: ./biopypir_utils.sh "LINT" 
    #===============================================#
    - name: BUILD
      id: builder
      run: ./biopypir_utils.sh  "BUILD"
    #===============================================#
    - name: PYTEST
      id: tester
      run: ./biopypir_utils.sh "TEST"  
    #===============================================#
    - name: PIP deployment test 
      continue-on-error: true
      id: pip_deploy_test
      if: "${{ env.PIP_TEST }}" 
      uses: BSFishy/pip-action@v1
      with:
        packages: "${{ env.PACKAGE }}"
        
    - name: Check Pip Test Result
      run: |
        if [ "${{ steps.pip_deploy_test.conclusion }}"  = "success" ]; then
              echo "pip_test_result=True" >> $GITHUB_ENV
        elif [ ${{ steps.pip_deploy_test.conclusion }} = 'failure' ]; then
              echo "pip_test_result=False" >> $GITHUB_ENV
        elif [ ${{ steps.pip_deploy_test.conclusion }} = 'skipped' ]; then
              echo "pip_test_result=Package Not On PIP" >> $GITHUB_ENV
        fi     
    #===============================================#
    - name: validate-license-action
      continue-on-error: true
      id: check_license
      if: runner.os == 'Linux'
      uses: datreeio/validate-license-action@v1.0.0 
      with:
        args: 'MIT, ISC, BSD'
    #===============================================#
    - name: Check License Test Result
      run: |
        if [ "${{ steps.check_license.conclusion }}"  = "success" ]; then
              echo "License_result=True" >> $GITHUB_ENV
        elif [ ${{ steps.check_license.conclusion }} = 'failure' ]; then
              echo "License_result=False" >> $GITHUB_ENV
        fi
  #===============================================#
    - name: GATHER outputs # removed and license check passing steps
      #continue-on-error: true
      run: |
        ./biopypir_utils.sh "GATHER" "${{matrix.python-version}}" "${{matrix.os}}" \
        "${{steps.linter.outputs.pylint_score}}" \
        "${{steps.tester.outputs.pytest_score}}" \
         "${{ env.pip_test_result }}" \
         "${{ env.License_result }}"
  #===============================================#
    - name: Make env var artifact for job 2
      run: echo env
   #===============================================#
    - name: UPLOAD artifact
      uses: actions/upload-artifact@v2-preview
      with:  
        name: biopypir-${{matrix.os}}-py${{matrix.python-version}}
        path: biopypir-*.json


  job2:
      needs: [run_tests] 
      if: always()
      runs-on: ubuntu-latest
      steps:
        - name: Check-Out Repo #  checkout biopypir_logs repo, not scedar/manubot/etc.
          uses: actions/checkout@v2
          with:
            ref: logs_branch        # checking out logs_branch,  NOT default !!!
         #===============================================# 
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: '3.7'
        #===============================================# 
        - name: Download artifact
          uses: actions/download-artifact@v2-preview 
          with: # version2 automatically downloads all artifacts in path
            path: parallel_runs/
        #===============================================#
        - name: check for any job success, and cURL helper script
          run: |  
            curl -L -o biopypir_utils.sh "https://raw.githubusercontent.com/benstear/biopypir_logs/master/utils/workflow_helper.sh"      
            chmod +x biopypir_utils.sh
        #===============================================#
        - name: EVALUATE TEST RESULTS
          run: ./biopypir_utils.sh "EVALUATE"
        #===============================================#
        - name: GET REPO STATISTICS
          run:  ./biopypir_utils.sh "STATISTICS"
        #===============================================#
        #- name: UPLOAD Badge Color as artifact
        #  uses: actions/upload-artifact@v2-preview
        #  with:  
        #   name: badge.json
        #   path: badge.json
        #===============================================#
        - name: print env
          run: printenv
        
        - name: ${{ env.BADGE }}
          run: |
            echo ${{env.GITHUB_RUN_ID}}
            (curl -X GET -s https://api.github.com/repos/biopypir_logs/actions/runs/${{env.GITHUB_RUN_ID}}/jobs) > jobs.json
            badge_color=$(cat jobs.json | jq .jobs[3].steps[5].name);
            badge_color2=$(cat jobs.json | jq .jobs[3].steps[6].name);
            echo $badge_color
            echo $badge_color2
        - name: Report badge image generation
          run:  |
            curl -L -o generate_badge.sh "https://raw.githubusercontent.com/benstear/biopypir_logs/master/utils/generate_badge_url.sh"      
            chmod +x generate_badge.sh
            ./generate_badge.sh
       #===============================================#
        - name: CLEAN UP
          run: ./biopypir_utils.sh "CLEAN UP"
       #===============================================# 
        - name: DELETE ARTIFACTS
          uses: geekyeggo/delete-artifact@1-glob-support    # need this again, after uploading badge SVG? 
          with:                                             # or can we put it at the end once?
              name: biopypir-*
              useGlob: true 
       #===============================================#   
        - name: do git pull # need this everytime?
          run: |
            git config pull.rebase false
            git pull
       #===============================================# 
        - name: Add & Commit 
          #if: always()
          uses: EndBug/add-and-commit@v4.1.0
          with:
            add: . #logs/  #${{env.PACKAGE}}_${{github.run_id}}.json
            author_name: GitHub Actions
            message: 'Commit ${{env.PACKAGE}} workflow run # ${{github.run_number}}  (${{env.biopypir_workflow_status}})'
            ref: 'logs_branch' 
            #force: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 


