

---
name: DISPATCH
on: 
  schedule:
    - cron: '0 0 * * 0' 
  push: # remove when youre done testing workflow
jobs:
  trigger_scedar_workflow:
    runs-on:  [ubuntu-latest] 
    #env:       
    #  PACKAGE: scedar  
    #============================================#
    steps:
    #- name:  Get env vars
    #  id: get_vars
    #  run: |
    #    curl -L -o env_vars.json https://raw.githubusercontent.com/benstear/biopypir_logs/master/utils/scedar_params.json
    #    ls -A  
    #   echo "::set-output name=env_vars::$(cat env_vars.json)"

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: benstear/biopypir_logs
          event-type: autorun
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'   
          
    #- name: Repository Dispatch
    #  uses: peter-evans/repository-dispatch@v1
    #  with:
    #    token: ${{ secrets.REPO_ACCESS_TOKEN }}
    #    repository: benstear/biopypir_logs
    #    event-type: autorun    
    #client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}","PACKAGE": "scedar" ,  "OWNER":  "TaylorResearchLab" ,  "Owner_Repo": "TaylorResearchLab/scedar", "test_suite" :  "pytest" , "tests_dir":  "tests/" , "ignore_tests": "None", "ignore_lint": "None"}' #, "python-version" :  [3.6, 3.7], "os"  : ["ubuntu-latest", "macOS-latest"] }'
              
        
      
        #'{ "PACKAGE": "scedar" ,
        #                  "OWNER":  "TaylorResearchLab" ,
        #                  "Owner_Repo": "TaylorResearchLab/scedar",
        #                  "test_suite" :  "pytest" ,
        #                  "tests_dir":  "tests/" ,
        #                  "ignore_tests": "None",
        #                   "ignore_lint": "None",
        #                  "python-version" :  [3.6, 3.7],
        #                    "os"  : ["ubuntu-latest", "macOS-latest"]
         #}
           





