

---
name: DISPATCH
on: 
  schedule:
    - cron: '0 0 * * 0' 
  push: # remove when youre done testing workflow
jobs:
  trigger_workflow:
    runs-on:  [ubuntu-latest] 
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: benstear/biopypir_logs
          event-type: autorun
          #client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}","PACKAGE": "scedar" ,  "OWNER":  "TaylorResearchLab" ,  "Owner_Repo": "TaylorResearchLab/scedar", "test_suite" :  "pytest" , "tests_dir":  "tests/" , "ignore_tests": "None", "ignore_lint": "None",pip: True}' #, "python-version" :  [3.6, 3.7], "os"  : ["ubuntu-latest", "macOS-latest"] }'
          #client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}","PACKAGE": "desc"  , "OWNER":  "eleozzr", "Owner_Repo": "eleozzr/desc","test_suite" :"None","tests_dir":  "None" ,"ignore_tests": "None", "ignore_lint": "None",pip: True}' #,"python-version" : [3.6, 3.7], "os"  : ["ubuntu-latest", "macOS-latest"]}'
          #client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}","PACKAGE": "scTDA" ,"OWNER":  "CamaraLab" ,  "Owner_Repo":  "CamaraLab/scTDA", "test_suite" :  "None" ,"tests_dir":  "None" , "ignore_tests": "None", "ignore_lint": "None",pip: True}' #, "python-version" :  [3.6, 3.7], "os"  : ["ubuntu-latest", "macOS-latest"] }'
          #client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}","PACKAGE": "BackSPIN" ,"OWNER":  "linnarsson-lab" ,  "Owner_Repo":  "linnarsson-lab/BackSPIN", "test_suite" :  "None" ,"tests_dir":  "None" , "ignore_tests": "None", "ignore_lint": "None",pip: True}' #, "python-version" :  [3.6, 3.7], "os"  : ["ubuntu-latest", "macOS-latest"] }'
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}","PACKAGE": "cellranger" ,"OWNER":  "10XGenomics" ,"Owner_Repo":  "10XGenomics/cellranger","test_suite" :  "None" ,"tests_dir":  "None" ,"ignore_tests": "None", "ignore_lint": "None", "pip": "False"}' #, "python-version" :  [3.6, 3.7], "os"  : ["ubuntu-latest", "macOS-latest"] }'
          #client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}","PACKAGE": "scLVM" ,"OWNER":  "PMBio" ,  "Owner_Repo":  "PMBio/scLVM", "test_suite" :  "None" ,"tests_dir":  "None" , "ignore_tests": "None", "ignore_lint": "None",pip: True}' #, "python-version" :  [3.6, 3.7], "os"  : ["ubuntu-latest", "macOS-latest"] }'
          #client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}","PACKAGE": "scanpy" ,"OWNER":  "theislab" ,  "Owner_Repo":  "theislab/scanpy", "test_suite" :  "None" ,"tests_dir":  "None" , "ignore_tests": "None", "ignore_lint": "None",pip: True}' #, "python-version" :  [3.6, 3.7], "os"  : ["ubuntu-latest", "macOS-latest"] }'


