

---
name: BIOPYPIR
on: 
  schedule:
    - cron: '0 0 * * 0' 
  push: # remove when youre done testing workflow
jobs:
  trigger_biopypir_workflows:
    runs-on:  [ubuntu-latest] 
    #============================================#
    #env:       
    #  PACKAGE: scedar  
    #============================================#
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: benstear/biopypir_logs
        event-type: autorun
        client-payload:   |
          '{ "PACKAGE": "scedar" ,  
            "OWNER":  "TaylorResearchLab" ,
             "Owner_Repo": "TaylorResearchLab/scedar",
            "test_suite" :  "pytest" ,
            "tests_dir":  "tests/" ,
            "ignore_tests": "None",
            "ignore_lint": "None",
            "python-version" :  [3.6, 3.7],
            "os"  : ["ubuntu-latest", "macOS-latest"]
            }'
        #client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'





