

---
name: DISPATCH
on: 
  schedule:
    - cron: '0 0 * * 0' 
  push: # remove when youre done testing workflow
jobs:
  trigger_scedar_workflow:
    runs-on:  [ubuntu-latest] 
    steps:
    - name: scedar autorun Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: benstear/biopypir_logs
          event-type: repository dispatch scedar
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}","PACKAGE": "scedar" ,  "OWNER":  "TaylorResearchLab" ,  "Owner_Repo": "TaylorResearchLab/scedar", "test_suite" :  "pytest" , "tests_dir":  "tests/" , "ignore_tests": "None", "ignore_lint": "None"}' #, "python-version" :  [3.6, 3.7], "os"  : ["ubuntu-latest", "macOS-latest"] }'
  
  trigger_desc_workflow:
   runs-on: [ubuntu-latest]
   steps:
     - name: desc autorun Repository Dispatch
       uses: peter-evans/repository-dispatch@v1
       with:
            token: ${{ secrets.REPO_ACCESS_TOKEN }}
            repository: benstear/biopypir_logs
            event-type: repository dispatch desc
            client-payload: '{"PACKAGE": "desc"  , "OWNER":  "eleozzr", "Owner_Repo": "eleozzr/desc","test_suite" :"None","tests_dir":  "None" ,"ignore_tests": "None", "ignore_lint": "None"}' #,"python-version" : [3.6, 3.7], "os"  : ["ubuntu-latest", "macOS-latest"]}'
            #client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}","PACKAGE": "scedar" ,  "OWNER":  "TaylorResearchLab" ,  "Owner_Repo": "TaylorResearchLab/scedar", "test_suite" :  "pytest" , "tests_dir":  "tests/" , "ignore_tests": "None", "ignore_lint": "None"}' #, "python-version" :  [3.6, 3.7], "os"  : ["ubuntu-latest", "macOS-latest"] }'
            #client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}","PACKAGE": "manubot" ,  "OWNER":  "cgreene" ,  "Owner_Repo":  "cgreene/manubot", "test_suite" :  "pytest" , "tests_dir":  "manubot" , "ignore_tests": "None", "ignore_lint": "None"}' #, "python-version" :  [3.6, 3.7], "os"  : ["ubuntu-latest", "macOS-latest"] }'





