---
name: BIOPYPIR-APPROVED
on: 
  schedule:
    - cron: '0 0 * * 0' 
  push: # remove when youre done testing workflow
jobs:
  biopypir_testing:
    runs-on: ${{ matrix.os }}
    strategy:
      #fail-fast: false
      matrix:
        python-version: [3.6,3.7] 
        os: [macOS-latest, ubuntu-latest] 
    env: 
      REPO: ${{ github.repository }}    # benstear/biopypir_logs, prob dont need this anymore
      RUN_ID: ${{ github.run_id }}
      PACKAGE: scedar
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT" > GITHUB_CONTEXT.json
        echo " run #: ${{github.run_number}}"
        echo " sha: ${{github.sha}}"
    
    #===============================================#
    - name: checkout scedar repo 
      uses: actions/checkout@v2     
      with:
        repository: benstear/${{ env.PACKAGE }}
    #===============================================#
    - run: |
        curl -L -o biopypir_utils.sh "https://raw.githubusercontent.com/benstear/biopypir_logs/master/.github/workflows/${{ env.PACKAGE }}_helper.sh"      
        chmod +x biopypir_utils.sh  
    #===============================================#
    - name: Set Up ${{matrix.os}}-py${{matrix.python-version}}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}   
    #- name: check license
    #  if: startsWith(matrix.os, 'ubuntu')
    #  uses: benstear/validate-license-action
    #  with:
    #    args: "MIT,ISC,BSD"  #"Apache License 2.0, MIT, ISC"    
    #===============================================#
    - name: INSTALL dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install --no-binary :all: nmslib   
        pip install pylint
        pip install pytest
        pip install pytest-cov
        pip install pytest-mpl
        pip install .
    #===============================================#
    - name: LINT
      id: linter
      run: ./biopypir_utils.sh "LINT" "${{ env.PACKAGE }}"
    #===============================================#
    - name: BUILD
      id: builder
      run: |
        ./biopypir_utils.sh  "BUILD"
    #===============================================#
    - name: PYTEST
      id: local
      run: |
        ./biopypir_utils.sh "TEST" ${{ env.PACKAGE }}; 
   #===============================================#
    - name: PIP deployment test 
      uses: BSFishy/pip-action@v1
      with:
        packages: "${{ env.PACKAGE }}"
    #===============================================#
    - name: GATHER outputs # removed pytest,pip deploy and license check passing steps
      continue-on-error: true
      run: |
       ./biopypir_utils.sh "GATHER"  \
        "${{matrix.python-version}}" "${{matrix.os}}" \
        "${{steps.linter.outputs.pylint-score}}" "${{steps.local.outputs.pytest_score}}" "True" "True"
   #===============================================#
    - name: UPLOAD artifact
      uses: actions/upload-artifact@v2-preview
      with:  
        name: biopypir-${{matrix.os}}-py${{matrix.python-version}}
        path: biopypir-*.json
    - name: UPLOAD second artifact
      uses: actions/upload-artifact@v2-preview
      with:  
        name: GITHUB_CONTEXT.json
        path: GITHUB_CONTEXT.json

        
  job2:
      needs: [biopypir_testing] 
      if: always()
      runs-on: [ubuntu-latest]
      env:
        PACKAGE: scedar
      steps:
        - name: Check-Out Repo 
          uses: actions/checkout@v2 
        #===============================================# 
        - name: Download artifact
          uses: actions/download-artifact@v2-preview 
          with: # version2 automatically downloads all artifacts in path
            path: parallel_runs/
        - name: list artifacts
          run: |
            pwd; ls -R;
            curl -L -o biopypir_utils.sh "https://raw.githubusercontent.com/benstear/biopypir_logs/master/.github/workflows/${{ env.PACKAGE }}_helper.sh"      
            chmod +x biopypir_utils.sh
        #===============================================#
        - name: EVALUATE jobs
          run: ./biopypir_utils.sh "EVAL" "benstear/biopypir_logs" "${{github.run_id}}"
        - uses: geekyeggo/delete-artifact@v1
          with:
            name: |
              biopypir-ubuntu-latest-py3.6
              biopypir-ubuntu-latest-py3.7
              biopypir-macOS-latest-py3.6
              biopypir-macOS-latest-py3.7

        - run: cat final.json
        #=============================================# 
        #- name: UPLOAD final json artifact
        #  uses: actions/upload-artifact@v2-preview
        #  with:  
        #    name: API.json
        #    path: API.json
        
        - name: STATS
          run: ./biopypir_utils.sh "STATS"
          
        - run: ls -aR
        #- name: GitHub Push
        #  uses: ad-m/github-push-action@v0.5.0
        #  with:
        #    github_token: ${{ secrets.GITHUB_TOKEN }}
        
        #===============================================#
        - name: Commit 
          env:
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
              git config --global user.email "bjs385@drexel.edu"    
              git config --global user.name "benstear"
              echo "Sending json log to biopypir_logs/logs"
              git pull https://github.com/benstear/biopypir_logs.git
              mv payload_${{github.run_id}}.json logs/
              git add logs/payload_${{github.run_id}}.json
              git pull -m 'commit ${{env.PACKAGE}} workflow log # ${{github.run_id}}'
              git push
          #mv final.json biopypir_logs #cd biopypir_logs
          # clone, delete files in the clone, and copy (new) files over
          # this handles file deletions, additions, and changes seamlessly
          #git clone --depth 1 https://$API_TOKEN_GITHUB@github.com/$GITHUB_USERNAME/$NAME.git $CLONE_DIR &> /dev/null
          #cd $CLONE_DIR
          #find . | grep -v ".git" | grep -v "^\.*$" | xargs rm -rf # delete all files (to handle deletions in monorepo)
          #cp -r $BASE/$folder/. .

            #mkdir temp_git
            #cd temp_git
            #git init   #  add .git folder and initialize 
            #git remote add origin  https://github.com/benstear/biopypir_logs.git # connect to a repo
            #git pull origin master # pull repo to local 
        #===============================================#
        #- name: Global webhook
        #  if: always() 
        #  uses: muinmomin/webhook-action@v1.0.0
        #  with:
        #    url: ${{ secrets.WEBHOOK_URL }}
        #    data: final.json   
        #- name: Webhook
        #  uses: joelwmale/webhook-action@master
        #  env:
        #    WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        #    data: final.json
