---
name: BIOPYPIR
on: 
  schedule:
    - cron: '0 0 * * 0' 
  push: # remove when youre done testing workflow
jobs:
  run_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6,3.7] 
        os: [macOS-latest, ubuntu-latest] 
    env:       
      PACKAGE: scedar #RUN_ID: ${{ github.run_id }}
    steps:
    #- name: Dump GitHub context
      #env:
      #  GITHUB_CONTEXT: ${{ toJson(github) }}
      #run: |
      #  cat "$GITHUB_CONTEXT" > GITHUB_CONTEXT.json
      #  ls
      #  echo " run #: ${{github.run_number}}"
      #  echo " sha: ${{github.sha}}"
    #===============================================#
    - name: checkout scedar repo 
      uses: actions/checkout@v2     
      with:
        repository: benstear/${{ env.PACKAGE }}
    #===============================================#
    - run: |
        curl -L -o biopypir_utils.sh "https://raw.githubusercontent.com/benstear/biopypir_logs/master/.github/workflows/${{ env.PACKAGE }}_helper.sh"      
        chmod +x biopypir_utils.sh  
    #===============================================#
    - name: Set Up ${{matrix.os}}-py${{matrix.python-version}}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}   
    - name: check license
      if: startsWith(matrix.os, 'ubuntu')
      uses: benstear/validate-license-action@master
      with:
        args: "MIT,ISC,BSD"  #"Apache License 2.0, MIT, ISC"    

    #===============================================#
    - name: INSTALL dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install --no-binary :all: nmslib   
        pip install pylint
        pip install pytest
        pip install pytest-cov
        pip install pytest-mpl
        pip install .
    #===============================================#
    - name: LINT
      id: linter
      run: ./biopypir_utils.sh "LINT" "${{ env.PACKAGE }}"
    #===============================================#
    - name: BUILD
      id: builder
      run: |
        ./biopypir_utils.sh  "BUILD"
    #===============================================#
    - name: PYTEST
      id: local
      run: |
        ./biopypir_utils.sh "TEST" ${{ env.PACKAGE }}; 
   #===============================================#
    - name: PIP deployment test 
      uses: BSFishy/pip-action@v1
      with:
        packages: "${{ env.PACKAGE }}"
    #===============================================#
    - name: GATHER outputs # removed pytest,pip deploy and license check passing steps
      continue-on-error: true
      run: |
       ./biopypir_utils.sh "GATHER"  \
        "${{matrix.python-version}}" "${{matrix.os}}" \
        "${{steps.linter.outputs.pylint-score}}" "${{steps.local.outputs.pytest_score}}" "True" "True"
   #===============================================#
    - name: UPLOAD artifact
      uses: actions/upload-artifact@v2-preview
      with:  
        name: biopypir-${{matrix.os}}-py${{matrix.python-version}}
        path: biopypir-*.json
    #- name: UPLOAD second artifact
    #  uses: actions/upload-artifact@v2-preview
    #  with:  
    #    name: GITHUB_CONTEXT.json
    #    path: GITHUB_CONTEXT.json
  job2:
      needs: [run_tests] 
      if: always()
      runs-on: [ubuntu-latest]
      env:
        PACKAGE: scedar
      steps:
        - name: Check-Out Repo 
          uses: actions/checkout@v2 
        #===============================================# 
        - name: Download artifact
          uses: actions/download-artifact@v2-preview 
          with: # version2 automatically downloads all artifacts in path
            path: parallel_runs/
        - name: list artifacts
          run: |
            pwd; ls -R;
            curl -L -o biopypir_utils.sh "https://raw.githubusercontent.com/benstear/biopypir_logs/master/.github/workflows/${{ env.PACKAGE }}_helper.sh"      
            chmod +x biopypir_utils.sh
        #===============================================#
        - name: EVALUATE jobs
          run: ./biopypir_utils.sh "EVAL" "benstear/biopypir_logs" "${{github.run_id}}"
        - uses: geekyeggo/delete-artifact@v1
          with:
            name: |
              biopypir-ubuntu-latest-py3.6
              biopypir-ubuntu-latest-py3.7
              biopypir-macOS-latest-py3.6
              biopypir-macOS-latest-py3.7
        - name: STATS
          run: ./biopypir_utils.sh "STATS"
          
        - run: ls -aR
        
        - name: Add & Commit
          uses: EndBug/add-and-commit@v4.1.0
          with:
            add: logs/payload_${{github.run_id}}.json
            message: 'Commit ${{env.PACKAGE}} workflow log # ${{github.run_id}}'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
 
